### ISSUE TITLE
Global leak: code

### ISSUE THREAD

**Issue by garthk** [joepie91/node-bhttp#1]
```
$ node
> global.code
undefined
> var bhttp = require('bhttp')
undefined
> global.code
'511'
```

**Comment by joepie91** [comment]
I suspect that's caused by the `errors` dependency. I'll have a look into it, and file a bug there if necessary.

**Comment by joepie91** [comment]
The issue was indeed with the `errors` dependency, I've submitted a pull request there that fixes it.

If this is a breaking issue for you, a workaround along the lines of the following (untested) should work, until it's fixed upstream:

```javascript
if (typeof global.code !== "undefined") { var oldCode = global.code; }
var bhttp = require("node-bhttp");
if (typeof oldCode !== "undefined") { global.code = oldCode; }
```

**Comment by joepie91** [comment]
An update for `errors` has been pushed to npm, that should solve this problem.
