### ISSUE TITLE
npm audit is reporting some vulnerabilities for this dependency

### ISSUE THREAD

**Issue by ariellyciandt** [joepie91/node-bhttp#41]
## Issue
There are some vulnerabilities reported by `npm audit` when we use the latest version of this module.

## Version: 
**1.2.4**
## Tested in 
**Aug 2nd, 2019**

## Vulnerabilities reported
|Level|Module|Path|Issue|Advisory|
|-|-|-|-|-|
|High|string|bhttp > string|Regular Expression Denial of Service|https://nodesecurity.io/advisories/536|
|Low|lodash|bhttp > form-data2 > lodash|Prototype Pollution|https://nodesecurity.io/advisories/577|
|Low|lodash|bhttp > lodash|Prototype Pollution|https://nodesecurity.io/advisories/577|
|Low|lodash|bhttp > form-data2 > lodash|Prototype Pollution|https://nodesecurity.io/advisories/782|
|High|lodash|bhttp > lodash|Prototype Pollution|https://nodesecurity.io/advisories/782|
|High|lodash|bhttp > form-data2 > lodash|Prototype Pollution|https://nodesecurity.io/advisories/1065|
|High|lodash|bhttp > lodash|Prototype Pollution|https://nodesecurity.io/advisories/1065|

## Prints
![image](https://user-images.githubusercontent.com/49289530/62376034-1c498900-b516-11e9-9b44-332e29a68ac8.png)
![image](https://user-images.githubusercontent.com/49289530/62376055-279cb480-b516-11e9-9d5f-02910742fbb4.png)
![image](https://user-images.githubusercontent.com/49289530/62376080-32efe000-b516-11e9-9342-bb267252169f.png)

**Comment by joepie91** [comment]
Thanks for the report! While none of these vulnerabilities ever actually affected bhttp (I checked this when they were originally reported, but forgot to make note of it here), I've just released a new version (of both `bhttp` and `form-data2`) that resolves these audit warnings. Once you upgrade to `1.2.6`, the warnings should be all gone.
